---
- name: Get timedatectl information
  ansible.builtin.command: timedatectl
  register: timedatectl
  ignore_errors: true
  changed_when: false

- ansible.builtin.include_tasks:
    file: timedatectl.yml
  when: timedatectl.rc is defined and timedatectl.rc == 0

- ansible.builtin.include_tasks:
    file: oldway.yml
  when: timedatectl.rc is defined and timedatectl.rc != 0
