---
- name: Stat timezone file
  stat:
    path: "/usr/share/zoneinfo/{{ timezone }}"
  register: tzcheck

- name: Check if timezone is valid
  fail:
    msg: "Invalid timezone given, given timezone was {{ timezone }}\"."
  when: tzcheck.stat is defined and tzcheck.stat.exists

- name: Link timezone info to etc
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    path: /etc/localtime
    state: link
    owner: root
    group: root
  register: tzlink
  notify:
    - Reconfigure tzdata
